project:
  type: book
  output-dir: docs
  
book:
  title: "Tidy Finance with R: Some notes"
  author: "Ian Gow"
  date: today
  date-format: "D MMMM YYYY"
  
  chapters:
    - index.qmd
    - chapter_1.qmd
    - fin_data.qmd
    - wrds.qmd
    - other-data.qmd
    - betas.qmd
    - uni-sorts.qmd
    - size-sorts.qmd
    - size-sorts-orig.qmd
    - value-bivariate-sorts.qmd
    - value-bivariate-sorts-orig.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo